name: Automated Builds
on: [push, workflow_dispatch]
jobs:
  win32-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure
        run: cmake -S . -B _build
      - name: Build
        run: cmake --build _build --config Release
      - name: Archive Win32 Package
        uses: actions/upload-artifact@v4
        with:
          name: pixelview_win32
          path: _build/Release/pixelview.exe
